# Research Workflow
# Coordinates traditions-scholar, clinical-researcher, and mechanisms-neuroscientist

name: research-workflow
version: 1.0.0
description: |
  Orchestrates comprehensive healing research by coordinating three
  specialized research agents to produce integrated research briefs.

# ═══════════════════════════════════════════════════════════════════════════════
# WORKFLOW STAGES
# ═══════════════════════════════════════════════════════════════════════════════

stages:
  - name: intake
    description: Parse research request and determine scope
    agent: orchestrator
    actions:
      - parse_query
      - determine_traditions
      - identify_clinical_questions
      - set_depth_level

  - name: traditions_research
    description: Research traditional healing practices and sources
    agent: traditions-scholar
    parallel: true
    inputs:
      - query
      - identified_traditions
    outputs:
      - traditions-research.md
      - primary_sources
      - cross_cultural_parallels

  - name: clinical_research
    description: Systematic review of clinical evidence
    agent: clinical-researcher
    parallel: true
    inputs:
      - query
      - clinical_questions
    outputs:
      - clinical-evidence.md
      - evidence_level
      - key_studies
      - safety_considerations

  - name: mechanism_mapping
    description: Bridge traditional and scientific frameworks
    agent: mechanisms-neuroscientist
    inputs:
      - traditions_research_output
      - clinical_research_output
    outputs:
      - mechanism-bridges.md
      - translation_notes
      - unexplained_aspects

  - name: synthesis
    description: Integrate all research into comprehensive brief
    agent: orchestrator
    inputs:
      - traditions_research_output
      - clinical_research_output
      - mechanism_mapping_output
    outputs:
      - research-brief.md

  - name: ethics_review
    description: Review research outputs for ethical concerns
    agent: ethics-guardian
    inputs:
      - research-brief.md
    outputs:
      - ethics_approval
      - concerns
      - required_modifications

# ═══════════════════════════════════════════════════════════════════════════════
# DEPTH LEVELS
# ═══════════════════════════════════════════════════════════════════════════════

depth_levels:
  quick:
    description: Rapid overview for initial scoping
    traditions_scholar:
      - Secondary sources acceptable
      - 1-2 traditions focus
      - Key historical context only
    clinical_researcher:
      - Systematic reviews only
      - Top 3 studies
      - Summary evidence level
    mechanisms_neuroscientist:
      - Primary mechanism only
      - Brief translation notes
    output: 2-3 page brief

  standard:
    description: Balanced research for typical needs
    traditions_scholar:
      - Primary sources preferred
      - 2-3 traditions
      - Full historical context
    clinical_researcher:
      - Systematic reviews + key RCTs
      - Full GRADE assessment
      - Safety review
    mechanisms_neuroscientist:
      - Multiple mechanisms
      - Integration notes
    output: 5-8 page brief

  comprehensive:
    description: Deep dive for complex topics
    traditions_scholar:
      - Primary sources required
      - All relevant traditions
      - Full lineage tracing
      - Cross-cultural analysis
    clinical_researcher:
      - Complete literature search
      - All study types
      - Meta-analytic summary
      - Full safety profile
    mechanisms_neuroscientist:
      - All proposed mechanisms
      - Evidence for each
      - Complete translation
      - Gap analysis
    output: 15-25 page brief

# ═══════════════════════════════════════════════════════════════════════════════
# INTEGRATION PATTERNS
# ═══════════════════════════════════════════════════════════════════════════════

integration:
  parallel_execution:
    - traditions_research
    - clinical_research

  sequential_execution:
    - intake → traditions_research + clinical_research
    - traditions_research + clinical_research → mechanism_mapping
    - mechanism_mapping → synthesis
    - synthesis → ethics_review

  data_flow:
    traditions_to_clinical:
      - Traditional claims for verification
      - Historical uses as search terms
      - Practice methodology for study design

    clinical_to_mechanisms:
      - Observed effects requiring explanation
      - Physiological measures
      - Unexplained findings

    traditions_to_mechanisms:
      - Traditional explanatory models
      - Described mechanisms
      - Phenomenological reports

# ═══════════════════════════════════════════════════════════════════════════════
# OUTPUT STRUCTURE
# ═══════════════════════════════════════════════════════════════════════════════

output_structure:
  research-brief.md:
    sections:
      - executive_summary
      - traditional_foundations
      - clinical_evidence
      - mechanism_understanding
      - integration_synthesis
      - practice_implications
      - safety_considerations
      - gaps_and_uncertainties
      - references

  traditions-research.md:
    sections:
      - overview
      - primary_sources
      - historical_development
      - traditional_methodology
      - cross_cultural_parallels
      - current_status
      - citations

  clinical-evidence.md:
    sections:
      - search_methodology
      - evidence_overview
      - key_studies
      - synthesis
      - safety
      - limitations
      - references

  mechanism-bridges.md:
    sections:
      - traditional_explanations
      - scientific_mechanisms
      - translation_notes
      - unexplained_aspects
      - integration_guidance

# ═══════════════════════════════════════════════════════════════════════════════
# QUALITY GATES
# ═══════════════════════════════════════════════════════════════════════════════

quality_gates:
  traditions_research:
    - Primary sources cited for key claims
    - Dates and eras documented
    - Cultural context preserved
    - Closed practices identified

  clinical_research:
    - Search strategy documented
    - Study quality assessed
    - Evidence level assigned
    - Limitations noted

  mechanism_mapping:
    - Both frameworks represented
    - Evidence levels for mechanisms
    - Uncertainties acknowledged
    - Reductive language avoided

  synthesis:
    - All components integrated
    - Coherent narrative
    - Appropriate qualifications
    - Ethics review passed

# ═══════════════════════════════════════════════════════════════════════════════
# ERROR HANDLING
# ═══════════════════════════════════════════════════════════════════════════════

error_handling:
  no_traditional_sources:
    action: document_gap
    message: "Traditional documentation unavailable or insufficient"
    continue: true

  no_clinical_evidence:
    action: document_gap
    message: "Clinical research lacking for this modality"
    continue: true
    note: "Absence of evidence ≠ evidence of absence"

  closed_practice:
    action: flag_and_redirect
    message: "This practice is closed/initiatory"
    continue: false
    suggest_alternatives: true

  ethics_concerns:
    action: halt_and_review
    message: "Ethics review identified concerns"
    continue: false
    require: manual_review

# ═══════════════════════════════════════════════════════════════════════════════
# EXAMPLE INVOCATIONS
# ═══════════════════════════════════════════════════════════════════════════════

examples:
  - name: Quick research on acupressure
    invocation: /healing-research "acupressure for hand healing" --depth quick
    expected_output:
      - 2-3 page research-brief.md
      - Key TCM points for hand
      - Top clinical studies
      - Primary mechanism

  - name: Comprehensive visualization research
    invocation: /healing-research "visualization for chronic pain" --depth comprehensive
    expected_output:
      - 15-25 page research-brief.md
      - Multiple traditions covered
      - Full literature review
      - Complete mechanism analysis

  - name: Specific tradition research
    invocation: /traditions-research "Psalm healing in Jewish tradition"
    expected_output:
      - traditions-research.md only
      - Primary sources from Jewish mystical texts
      - Historical development
      - Current practice status
